version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (*os.File).Close
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
  exclusions:
    rules:
      - linters:
          - gosec
        text: "G115"
      - path: "_test\\.go$"
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

run:
  issues-exit-code: 1
